<footer>
    <div id="footer1">
            <div id="nav_footer">
                <h2><span>EXPLORE</span></h2>
                <div id="explore_footer">
                    <p><a href="./home.php"><i class="fa-sharp fa-solid fa-angle-right"></i>Home</a></p>
                    <p><a href="./product.php"><i class="fa-sharp fa-solid fa-angle-right"></i>Product</a></p>
                    <p><a href="./transaction.php"><i class="fa-sharp fa-solid fa-angle-right"></i>Transaction</a></p>
                    <p><a href="./login.php"><i class="fa-sharp fa-solid fa-angle-right"></i>Cart</a></p>
                    <p><a href="./wallet.php"><i class="fa-sharp fa-solid fa-angle-right"></i>Connect Wallet</a></p>
                </div>
            </div>
            <div id="overall">
                <h2><span>ABOUT</span></h2>
                <p><a href="./home.php">The Company</a></p>
                <p><a href="#">FAQ</a></p>
                <p><a href="#">Privacy Policy</a></p>
            </div>
            <div id="icons">
                <h2><span>FOLLOW US</span></h2>
                <a href="#"><i class="fa-brands fa-facebook"></i></a>
                <a href="#"><i class="fa-brands fa-twitter"></i></a>
                <a href="#"><i class="fa-brands fa-youtube"></i></a>
            </div>
    </div>

    <div id="footer2">
            <p><i class="fa-solid fa-copyright"></i>2023 Foodie. ALL RIGHTS RESERVED.</p>
            <img src="images/logo.png" alt="logo">
    </div>
</footer>