<header>
      <!-- nav bar for the web -->
    <nav class="navbar">
          <!-- web logo -->
        <a class="navbar_brand" href="index.php">
          <img src="styles/images/Bookicon.png" alt="Logo" class="logo_image">
        </a>
        <?php include 'menu.inc'; ?>
          <!-- search bar -->
          <form class="form_inline">
            <input class="form_control" type="search" placeholder="Search" aria-label="Search" >
          </form>
        </div>
      
    </nav>
  </header>